logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
      hibernate:
        stat: debug
        type: trace
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
#Find out how to access profiles since this is causing the other yaml properties to not work such as the h2 and its console.
#  config:
#    activate:
#      on-profile: development
  resources:
    static-locations: classpath:/static/

name: Development Setup
riotApi: RGAPI-45db0f6e-7ecb-4feb-878d-bd2099c982a0
