logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    repositories:
      bootstrap-mode: default
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  config:
    activate:
      on-profile: development
  resources:
    static-locations: classpath:/static/

name: Development Setup
riotApi: RGAPI-6d31fd53-add1-4b35-a31f-c057880420ea
