name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          java-package: 'jdk'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Clean with maven
        run: mvn clean

      - name: Build with maven
        run: mvn -B package --file pom.xml

  publish:
    needs: build

---

name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main
